service: noservernovember-ipsum

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  stage: ${opt:stage, 'development'}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  ipsum:
    handler: bin/ipsum
    events:
       - http:
          path: ipsum
          method: GET


