service: noservernovember-ipsum

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  ipsum:
    handler: bin/ipsum
    events:
       - http:
          path: ipsum
          method: GET


